# Generated by Django 5.0.7 on 2024-08-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
    ]
